server:
  port: 8086
spring:
    datasource:
        url: jdbc:mysql://localhost:33066/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        hikari:
         username: root
         password: 123456
         driver-class-name: com.mysql.jdbc.Driver
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                #环境隔离
                #namespace: 2c75089f-8400-4320-9506-f48c153d8d17
                #NJ    指定集群名称
                #cluster-name: NJ
    application:
        #服务名称用-
        name: centent-center





